### ISSUE TITLE
BSScope.Backdoor.DarkComet 

### ISSUE THREAD

**Issue by Spartachris** [anotak/doombuilderx#16]
https://www.virustotal.com/#/file/d9e4a660922dafe17cff12bcfba7f653bc49f5e38d69cf106986fdde8809ee68/detection

Oddly specific for a false positive so I'm just really not sure about this. Are you aware of these?

Cylance - Unsafe

Sophos ML - heuristic

TrendMicro-HouseCall - PAK_Generic.005

VBA32 - BScope.Backdoor.DarkKomet

**Comment by anotak** [comment]
Yeah, someone brought it up before. It's really weird, but if you check every file individually, you get different results. The only files that make virustotal complain individually are the 3 nodebuilders, ZenNode, ZokumBSP, and GLBSP:

https://www.virustotal.com/#/file/da351e9ddb94480a1a8d98b36dd448b0fa28298d55bf9d4b3a48a8c749d5ef04/detection

https://www.virustotal.com/#/file/1581cd6a9541df0ab266861394c9860617ff39ae412e12c2dd4c19b357882063/detection

https://www.virustotal.com/#/file/c2a6317f66d97aa469a1b39f236f1319437cfff74a5f898581085d11d47ec9f2/detection

You'll notice that the virustotal for the individual files doesn't seem to include the specific warning. Yes, it's weird, but I think it's a false positive.

So I did not write the code in those 3 nodebuilders, but I've used them and they do not attempt to connect to the net as far as I can tell. All 3 are open source. I've actually looked at the ZenNode and ZokumBSP source myself (and contributed a minor patch to zokumbsp). ZenNode and GLBSP have been in use for a decade if not more without incident, and ZokumBSP is based on ZenNode.

Doom Builder X itself in its current form does not contain any source code for accessing the internet, to the best of my knowledge. Doom Builder 2's source code that it was based on is 50k lines of code, so I may have missed something, but I don't think I did.

Please let me know if you find out anything else about this. I take matters of computer security very seriously and they will always be the first priority to fix if they happen.  I haven't had an issue like that on this project yet though, aside from this.
