### ISSUE TITLE
Texture previews won't show up

### ISSUE THREAD

**Issue by marrub--** [anotak/doombuilderx#9]
![visual of bug](http://mab.greyserv.net/f/1544951410216.png)

Using High Contrast mode on Windows 10, texture previews in the sectors menu and in the sector info peek on the bottom just show up as black. The texture selector works fine and 2D/3D modes show the textures fine, just not these boxes.

(Note: I'm not actually sure if it's High Contrast mode doing this, but I can't test to see if it isn't, and it's the most likely case.)

**Comment by anotak** [comment]
hmm. that's really messed up. do the boxes on the bottom of the screen when you mouse over a sector/line in 2d mode work for you?

**Comment by anotak** [comment]
does this happen for you in GZDB-BF?

**Comment by anotak** [comment]
okay i see the problem. hm. this is a bit nasty but i will fix it.

**Comment by anotak** [comment]
ok i did [this commit](https://github.com/anotak/doombuilderx/commit/17af921923c99f28eabae84ebc240b1ce05d7c93), it should be fixed

i guess i'll upload a build for you to try out in a little bit?

**Comment by marrub--** [comment]
thanks!!

**Comment by anotak** [comment]
https://www.sf4remix.com/lilith/doombuilderx-2.1.3.11-alpha6.zip

try this out

**Comment by marrub--** [comment]
it works! thank you!

**Comment by anotak** [comment]
cool! np!
